language: ruby
rvm:
  - "1.9.3"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmagickwand-dev libvips-dev libmagic-dev graphicsmagick poppler-utils poppler-data ghostscript pdftk libreoffice

branches:
  only:
    - master
