version: '2'
services:
  # Back-end services
  memcached:
    image: memcached
  mongo:
    image: mongo
    volumes:
      - data-mongo:/data/db
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - data-redis:/data
  solr:
    image: oregondigital/solr
    ports:
      - "8983:8983"
    volumes:
      - data-solr-dev:/opt/solr/server/solr/mycores
  fc381:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    command: bash -c "rm -f /opt/jetty/webapps/solr.war && java -jar start.jar"
    ports:
      - "8984:8983"
    volumes:
      - data-fedora:/opt/jetty/fedora/default/data
      - data-derby:/opt/jetty/fedora/default/derby
      - ./media:/oregondigital/media
  workers:
    image: oregondigital/od1-dev
    build:
      dockerfile: docker/Dockerfile-dev
      context: .
    volumes:
      - .:/oregondigital
      - ./batch:/data1/batch
    entrypoint: ""
    command: bundle exec rake resque:work
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    env_file:
      - docker/web-variables.env
      - docker/resque-variables.env

  # This is just here to help facilitate building the OD1 image; it isn't
  # enabled when starting the web container
  core:
    image: oregondigital/od1
    entrypoint: /bin/false

  # Front-end stuff
  web:
    image: oregondigital/od1-dev
    build:
      dockerfile: docker/Dockerfile-dev
      context: .
    volumes:
      - .:/oregondigital
      - ./docker/dev-entry.sh:/entrypoint.sh
      - ./batch:/data1/batch
    ports:
      - "3000:3000"
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    env_file:
      - docker/web-variables.env
  resquehead:
    image: oregondigital/od1-dev
    build:
      dockerfile: docker/Dockerfile-dev
      context: .
    entrypoint: ""
    command: bundle exec resque-web -FL -r redis:6379
    ports:
      - "5678:5678"
    links:
      - redis
    env_file:
      - docker/web-variables.env
      - docker/resque-variables.env
  deepzoom:
    image: uolibraries/rais:2.8.0
    environment:
      - RAIS_IIIFURL=http://localhost:12415/images/iiif
      - RAIS_TILECACHELEN=100
    ports:
      - "12415:12415"
    volumes:
      - ./media/pyramidal-tiffs:/var/local/images
volumes:
  data-mongo: {}
  data-solr-dev: {}
  data-fedora: {}
  data-derby: {}
  data-redis: {}
