version: '2'
services:
  # Back-end services
  memcached:
    image: memcached
  mongo:
    image: mongo
  redis:
    image: redis
  solr:
    image: oregondigital/solr
  fc381:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    command: bash -c "rm -f /opt/jetty/webapps/solr.war && java -jar start.jar"
    volumes:
      - ./media:/oregondigital/media
    ports:
      - "18983:8983"

  # PhantomJS compiled binary - pull the image from Dockerhub if at all
  # possible - we don't tell compose how to build it because it's REALLY slow,
  # and we only need the compiled binary, AND it's only critical for testing.
  phantomjs:
    image: oregondigital/phantomjs:1.8.1
    command: cp bin/phantomjs /mnt/phantombin
    volumes:
      - ./phantombin:/mnt/phantombin

  # Actual test setup
  test:
    image: oregondigital/od1-test
    build:
      dockerfile: docker/Dockerfile-dev
      context: .
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    volumes:
      - .:/oregondigital
      - ./phantombin/phantomjs:/usr/bin/phantomjs
      - ./docker/test-entry.sh:/entrypoint.sh
    env_file:
      - docker/test-variables.env
