version: '2'
services:
  # Back-end services
  memcached:
    image: memcached
  mongo:
    image: mongo
  redis:
    image: redis
  solr:
    image: oregondigital/solr
  fc381:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    command: bash -c "rm -f /opt/jetty/webapps/solr.war && java -jar start.jar"
    ports:
      - "18983:8983"

  # PhantomJS compiled binary
  phantomjs:
    image: oregondigital/phantomjs
    build:
      dockerfile: docker/Dockerfile-phantomjs
      context: .
    command: ./go.sh
    volumes:
      - ./phantombin:/opt/phantomjs/bin

  # Actual test setup
  test:
    image: oregondigital/od1-test
    command: echo You must run tests manually!
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    depends_on:
      - phantomjs
    env_file:
      - docker/test-variables.env
