# -*- coding: utf-8 -*-
RSpec.configure do |config|
  config.before(:each) do
    stub_request(:get, "http://sws.geonames.org/5735237/").
      with(:headers => {'Accept'=>'application/n-triples, text/plain;q=0.5, application/rdf+xml, text/html;q=0.5, application/xhtml+xml, image/svg+xml, application/n-quads, text/x-nquads, application/ld+json, application/x-ld+json, application/json, text/n3, text/rdf+n3, application/rdf+n3, application/trig, application/x-trig, application/trix, application/turtle, text/rdf+turtle, text/turtle, application/x-turtle, */*;q=0.1', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Ruby'}).
        to_return(:status => 200, :body => '<http://sws.geonames.org/5735237/> <http://example.org/blah> "blah" .', :headers => {:'Content-Type' => 'application/n-triples'})

    stub_request(:get, "http://api.geonames.org/searchJSON?maxRows=20&q=blah&username=johnson.tom@gmail.com").
      with(:headers => {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip, deflate', 'User-Agent'=>'Ruby'}).
      to_return(:status => 200, :body => '{"totalResultsCount":7,"geonames":[{"countryId":"1562822","adminCode1":"00","countryName":"Vietnam","fclName":"stream, lake, ...","countryCode":"VN","lng":"107.56667","fcodeName":"stream","toponymName":"Ya Liau Blah","fcl":"H","name":"Ya Liau Blah","fcode":"STM","geonameId":1576042,"lat":"13.28333","adminName1":"","population":0},{"countryId":"1733045","adminCode1":"11","countryName":"Malaysia","fclName":"mountain,hill,rock,... ","countryCode":"MY","lng":"114.48333","fcodeName":"hill","toponymName":"Bukit Batu Belah","fcl":"T","name":"Bukit Batu Belah","fcode":"HLL","geonameId":1737928,"lat":"4.01667","adminName1":"Sarawak","population":0},{"countryId":"69543","adminCode1":"23","countryName":"Yemen","fclName":"spot, building, farm","countryCode":"YE","lng":"44.23528","fcodeName":"clinic","toponymName":"Al Markaz aş Şiḩḩīy bi Ḩubrānat Bilāḩ","fcl":"S","name":"Al Markaz aş Şiḩḩīy bi Ḩubrānat Bilāḩ","fcode":"HSPC","geonameId":7448130,"lat":"13.9512","adminName1":"Ibb","population":0},{"countryId":"1643084","adminCode1":"01","countryName":"Indonesia","fclName":"stream, lake, ...","countryCode":"ID","lng":"95.5176","fcodeName":"stream","toponymName":"Alue Blah","fcl":"H","name":"Alue Blah","fcode":"STM","geonameId":6706385,"lat":"5.3355","adminName1":"Aceh","population":0},{"countryId":"1733045","adminCode1":"11","countryName":"Malaysia","fclName":"stream, lake, ...","countryCode":"MY","lng":"113.93333","fcodeName":"stream","toponymName":"Sungai Belah","fcl":"H","name":"Sungai Belah","fcode":"STM","geonameId":1780249,"lat":"3.95","adminName1":"Sarawak","population":0},{"countryId":"1733045","adminCode1":"11","countryName":"Malaysia","fclName":"stream, lake, ...","countryCode":"MY","lng":"113.93333","fcodeName":"stream","toponymName":"Sungai Belah","fcl":"H","name":"Sungai Belah","fcode":"STM","geonameId":1780251,"lat":"3.93333","adminName1":"Sarawak","population":0},{"countryId":"1733045","adminCode1":"11","countryName":"Malaysia","fclName":"forest,heath,...","countryCode":"MY","lng":"114.48333","fcodeName":"forest(s)","toponymName":"Batu Belah Protected Forest","fcl":"V","name":"Batu Belah Protected Forest","fcode":"FRST","geonameId":1780902,"lat":"4.03333","adminName1":"Sarawak","population":0}]}', :headers => {'Content-Type' => 'application/json;charset=UTF-8'})

  end
end
