version: 2
jobs:
  build:
    docker:
      - image: lsat12357/ruby-phantomjs:0.0.1
        environment:
          - GI_TYPELIB_PATH: /usr/local/lib/girepository-1.0/
          - RAILS_ENV: test
          - OREGONDIGITAL_SOLR_HOST: http://127.0.0.1:8983/solr/development
          - OREGONDIGITAL_FEDORA_HOST: http://127.0.0.1:8983/fedora
      - image: circleci/mongo:3
      - image: redis

    parallelism: 3
    working_directory: ~/app
    steps:

      - run:
         name: Sudo
         command: apt-get install -y sudo

      - run:
          name: Services
          command: |
            sudo apt-get install -y memcached
            sudo service memcached restart

      - run:
          name: Bundler
          command: |
            gem install bundler
            bash -lc 'PATH="/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16:$PATH" gem install rmagick -v "2.13.2"'

      - checkout

      - restore_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install gems
          command: |
            bundle install

      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: DB
          command: bundle exec rake db:create db:migrate db:test:prepare

      - run:
          name: Jetty setup
          command: |
            mkdir -p tmp
            sudo apt-get install unzip
            bundle exec rake jetty:clean
            bundle exec rake jetty:config

      - run:
          name: Jetty start
          command: cd jetty && java -Djetty.port=8983 -Dsolr.solr.home=/home/ubuntu/oregondigital/jetty/solr -XX:MaxPermSize=128m -Xmx256m -jar start.jar
          background: true

      - run:
          name: Sets content
          command: bundle exec rake sets:content:sync

      - run:
          name: Phantomjs
          command: |
            cp /opt/phantomjs/bin/phantomjs /usr/bin/phantomjs

      - run:
          name: Asset dir
          command: |
            mkdir -p media/thumbnails
            ln -s media public/media
            ln -s media/thumbnails public/thumbnails

      - run:
          name: Sleep
          command: sleep 20

      - run:
          name: Rspec
          command: |
            RUBYOPT="-W0" rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/output \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: /tmp/test-results
  
          


