version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.1.10
        environment:
          - GI_TYPELIB_PATH: /usr/local/lib/girepository-1.0/
    working_directory: ~/app
    steps:
      - run:
          name: Libvips
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y pkg-config
            sudo apt-get install -y python-software-properties software-properties-common
            sudo apt-get install -y automake build-essential libgirepository1.0-dev \
                                    gtk-doc-tools libglib2.0-dev libturbojpeg1-dev \
                                    libpng12-dev libwebp-dev libtiff5-dev libexif-dev \
                                    libgsf-1-dev  liblcms2-dev libxml2-dev swig \
                                    libmagickcore-dev curl
            sudo mkdir -p /opt/libvips
            cd /opt/libvips
            curl -L https://github.com/jcupitt/libvips/releases/download/v8.4.6/vips-8.4.6.tar.gz | sudo tar zx
            cd /opt/libvips/vips-8.4.6
            configure --enable-debug=no --enable-docs=no --enable-cxx=yes --without-python --without-orc --without-fftw
            make
            make install
            lodconfig

      - run:
          name: Derivatives
          command: |
            sudo apt-get purge libreoffice*
            sudo add-apt-repository -y ppa:libreoffice/ppa
            sudo apt-get install -y poppler-utils poppler-data ghostscript libreoffice
            sudo apt-get install -y libmagic-dev libmagickwand-dev ffmpeg libavcodec-ffmpeg-extra56 libvorbis-dev
            sudo apt-get install -y graphicsmagick graphicsmagick-libmagick-dev-compat

      - run:
          name: Database connection libraries
          command: |
            sudo apt-get install -y libmysqlclient-dev
            sudo apt-get install -y libsqlite3-dev

      - run:
          name: Nodejs for compiling assets
          command: |
            sudo apt-get install -y nodejs

      - run:
          name: Git
          command: |
            sudo apt-get install -y git
      - run:
          name: Timezone info for Rails
          command: sudo apt-get install -y tzdata

      - run:
          name: Bundler
          command: |
            gem install bundler
            bash -lc 'PATH="/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16:$PATH" gem install rmagick -v "2.13.2"'

      - checkout

      - run:
          name: Install gems
          command: bundle install

      - run:
          name: DB
          command: bundle exec rake db:create db:migrate

      - run:
          name: Sets content
          command: bundle exec rake sets:content:sync

      - run:
          name: Jetty
          command: |
            bundle exec rake jetty:config
            bundle exec rake jetty:start
            sleep: 20

      - run:
         name: Rspec
         command: |
           bundle exec rspec --profile 10 \
                             --format RspecJunitFormatter \
                             --out /tmp/test-results/rspec.xml \
                             --format progress \
                             $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: /tmp/circle-junit
  
          


