version: 2
jobs:
  build:
    docker:
      - image: oregondigital/ruby-phantomjs:201912
        environment:
          - GI_TYPELIB_PATH: /usr/local/lib/girepository-1.0/
          - RAILS_ENV: test
          - OREGONDIGITAL_SOLR_HOST: http://localhost:8985/solr/development
          - OREGONDIGITAL_FEDORA_HOST: http://localhost:8983/fedora
      - image: circleci/mongo:3
      - image: redis
      - image: oregondigital/solr
        command: bin/solr -p 8985
      - image: oregondigital/hydra-jetty:3.8.1-4.0
        command: bash -lc 'rm -f /opt/jetty/webapps/solr.war && java -jar start.jar'

    working_directory: ~/app
    steps:

      - run:
         name: Sudo
         command: |
           apt-get update
           apt-get install -y sudo

      - run:
          name: Services
          command: |
            sudo apt-get install -y memcached
            sudo service memcached restart

      - run:
          name: Bundler
          command: |
            gem install bundler -v "1.17.3"
            bash -lc 'PATH="/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16:$PATH" gem install rmagick -v "2.13.2"'

      - checkout

      - restore_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install gems
          command: |
            bundle install

      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: DB
          command: bundle exec rake db:create db:migrate db:test:prepare

      - restore_cache:
          key: set_content-{{ .Branch }}

      - run:
          name: Sets content
          command: bundle exec rake sets:content:sync

      - save_cache:
          key: set_content-{{ .Branch }}
          paths: set_content

      - run:
          name: Phantomjs
          command: |
            cp /opt/phantomjs/bin/phantomjs /usr/bin/phantomjs

      - run:
          name: Asset dir
          command: |
            mkdir -p media/thumbnails
            ln -s media public/media
            ln -s media/thumbnails public/thumbnails

      - run:
          command: |
            mkdir tmp
            touch tmp/minter-state

      - run:
          name: Sleep
          command: sleep 10

      - run:
          name: Rspec
          command: |
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_controllers \
                              --format progress \
                             spec/controllers
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_decorators \
                              --format progress \
                              spec/decorators
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_features \
                              --format progress \
                              spec/features
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_helpers \
                              --format progress \
                              spec/helpers
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_jobs \
                              --format progress \
                              spec/jobs
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_lib \
                              --format progress \
                              spec/lib
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_services \
                              --format progress \
                              spec/services
            rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/test_views \
                              --format progress \
                              spec/views
            for TEST in spec/models/*_spec.rb; do \
                              rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/$TEST \
                              --format progress \
                              $TEST; done


      - store_artifacts:
          path: log/test.log
      - store_artifacts:
          path: tmp/capybara
      - store_artifacts:
          path: /tmp/test-results
      - store_test_results:
          path: /tmp/test-results
  
          


