version: 2
jobs:
  build:
    docker:
      - image: lsat12357/ruby-phantomjs:0.0.1
        environment:
          - GI_TYPELIB_PATH: /usr/local/lib/girepository-1.0/
      - image: circleci/mongo:3

    working_directory: ~/app
    steps:

      - run:
          name: Services
          command: |
            sudo apt-get install -y memcached

      - run:
          name: Bundler
          command: |
            gem install bundler
            bash -lc 'PATH="/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16:$PATH" gem install rmagick -v "2.13.2"'

      - checkout

      - run:
          name: Install gems
          command: bundle install

      - run:
          name: DB
          command: bundle exec rake db:create db:migrate

      - run:
          name: Sets content
          command: bundle exec rake sets:content:sync

      - run:
          name: Jetty
          command: |
            RAILS_ENV=development bundle exec rake jetty:clean
            bundle exec rake jetty:config
            bundle exec rake jetty:start
            sleep 20

      - run:
         name: Rspec
         command: |
           bundle exec rspec --profile 10 \
                             --format RspecJunitFormatter \
                             --out /tmp/test-results/rspec.xml \
                             --format progress \
                             $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: /tmp/circle-junit
  
          


