version: '2'
services:
  memcached:
    image: memcached
  mongo:
    image: mongo
    volumes:
      - od-data-mongo:/data/db
  redis:
    image: redis
  solr:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    command: bash -c "rm -f /opt/jetty/webapps/fedora.war && java -jar start.jar"
    volumes:
      - od-data-solr-dev:/opt/jetty/solr/development-core/data
      - ../solr_conf/solr.xml:/opt/jetty/solr/solr.xml
      - ../solr_conf/conf/schema.xml:/opt/jetty/solr/development-core/conf/schema.xml
      - ../solr_conf/conf/solrconfig.xml:/opt/jetty/solr/development-core/conf/solrconfig.xml
  fc381:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    command: bash -c "rm -f /opt/jetty/webapps/solr.war && java -jar start.jar"
    volumes:
      - od-data-fc:/opt/jetty/fedora/data
  web:
    image: oregondigital/od1
    volumes:
      - ../db:/oregondigital/db/
    ports:
      - "3000:3000"
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    env_file:
      - web-variables.env
volumes:
  od-data-mongo: {}
  od-data-solr-dev: {}
  od-data-fc: {}
