version: '2'
services:
  memcached:
    image: memcached
  mongo:
    image: mongo
    volumes:
      - od-data-mongo:/data/db
  redis:
    image: redis
  solr:
    image: makuk66/docker-solr:4.10.4
    volumes:
      - od-data-solr:/opt/solr
  fc381:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    volumes:
      - od-data-fc:/opt/fedora/data
  web:
    image: oregondigital/od1
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    volumes:
      - ../db:/oregondigital/db/
    ports:
      - "3000:3000"
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    env_file:
      - web-variables.env
volumes:
  od-data-mongo: {}
  od-data-solr: {}
  od-data-fc: {}
