# Creates an image suitable for running the Rails stack for OD 1.  This is for
# development at the moment; production Dockerizing will need tweaking to get
# all the code baked into an image, possibly set up safer settings, etc.
#
# Build:
#     docker build --rm -t oregondigital/od1 -f docker/Dockerfile-dev .

# TODO: Upgrade ubuntu!  Right now this just needs to work with what we have in
# circleci, but longer-term this could get problematic when ubuntu 12 hits EOL.
#
# Known issues:
# - VIPS install will need to be figured out for a newer Ubuntu
# - Will need to test derivative generation for all types since CLI changes sometimes happen
# - ffmpeg will need to be replaced, and libavcode-extra-53 definitely has to be replaced
FROM ubuntu:12.04
MAINTAINER Jeremy Echols <jechols@uoregon.edu>

# apt won't find some libs if this isn't run
RUN apt-get update

# Dependencies for vips installer
RUN apt-get install -y pkg-config
RUN apt-get install -y python-software-properties software-properties-common

# Vips!  This is very specific to Ubuntu 12.04, pulled out of vips-install.sh
RUN add-apt-repository -y ppa:lyrasis/precise-backports
RUN apt-get install -y automake build-essential gobject-introspection gtk-doc-tools libglib2.0-dev \
                       libjpeg-turbo8-dev libpng12-dev libwebp-dev libtiff4-dev libexif-dev \
                       libgsf-1-dev liblcms2-dev libxml2-dev swig libmagickcore-dev curl
RUN mkdir -p /opt/libvips
WORKDIR /opt/libvips
RUN curl http://www.vips.ecs.soton.ac.uk/supported/7.42/vips-7.42.3.tar.gz | tar zx
WORKDIR /opt/libvips/vips-7.42.3
RUN ./configure --enable-debug=no --enable-docs=no --enable-cxx=yes --without-python --without-orc --without-fftw
RUN make
RUN make install
RUN ldconfig

# Various derivative libs
RUN apt-get purge libreoffice*
RUN add-apt-repository -y ppa:libreoffice/ppa
RUN apt-get install -y poppler-utils poppler-data ghostscript libreoffice
RUN apt-get install -y libmagic-dev libmagickwand-dev ffmpeg libvorbis-dev libavcodec-extra-53

# Database connection libraries
RUN apt-get install -y libmysqlclient-dev
RUN apt-get install -y libsqlite3-dev

# Nodejs for compiling assets
RUN apt-get install -y nodejs

# We need git for all our github-hosted gems
RUN apt-get install -y git

# Dependencies for Ruby
RUN apt-get install -y libssl-dev libreadline-dev

# Grab Ruby manually - can't install the default for Ubuntu 12.04
#
# Make sure this comes after the big downloads, as it's more likely we'll
# change our ruby version than, say, our vips version - at least until we deal
# with a major change (like OS) that would require a ruby rebuild anyway
RUN mkdir -p /opt/ruby
WORKDIR /opt/ruby
RUN curl https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.5.tar.gz | tar zx
WORKDIR /opt/ruby/ruby-2.2.5
RUN ./configure
RUN make
RUN make install

# Set an environment variable to store where the app is installed to inside
# of the Docker image
ENV INSTALL_PATH /oregondigital
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

# Grab bundler for installing the gems
RUN gem install bundler

# Cache gem-building so we don't rebuild all the gems on every code change
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install

# Copy in OD code one piece at a time so we can trust what we end up with
ADD app app
ADD config config
ADD config.ru config.ru
ADD db db
ADD lib lib
ADD public public
ADD Rakefile Rakefile
ADD script script
ADD spec spec
ADD test test
ADD vendor vendor

# TODO: Figure out how to precompile assets before databases are ready

# Expose a volume so that the web server can read assets
VOLUME ["$INSTALL_PATH/public"]

# Allow devs to override the app code entirely
VOLUME ["$INSTALL_PATH/"]

# The default command runs the web server
CMD bundle exec rails s -p 3000 -b "0.0.0.0"
