version: '2'
services:
  memcached:
    image: memcached
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
  solr:
    image: oregondigital/solr
    ports:
      - "8983:8983"
    volumes:
      - solr-dev:/opt/solr/server/solr/mycores
  fc381:
    image: oregondigital/hydra-jetty:3.8.1-4.0
    command: bash -c "rm -f /opt/jetty/webapps/solr.war && java -jar start.jar"
    volumes:
      - fedora:/opt/jetty/fedora/data
  web:
    image: oregondigital/od1
    volumes:
      - ../db:/oregondigital/db/
    command: bash -c "rm -f /oregondigital/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    links:
      - memcached
      - redis
      - mongo
      - solr
      - fc381
    env_file:
      - web-variables.env
volumes:
  mongo: {}
  solr-dev: {}
  fedora: {}
  redis: {}
