# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora.
development:
  url: <%= ENV['OREGONDIGITAL_SOLR_HOST'] || "http://localhost:8983/solr/development" %>
test: &TEST
  url: <%= ENV['OREGONDIGITAL_SOLR_HOST'] || "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
cucumber:
  <<: *TEST
production:
  url: <%= ENV['OREGONDIGITAL_SOLR_HOST'] || "http://your.production.server:8080/bl_solr/core0" %>
staging:
  url: <%= ENV['OREGONDIGITAL_SOLR_HOST'] || "http://your.production.server:8080/bl_solr/core0" %>
