module OregonDigital::Vocabularies
  ##
  # MARC Relators
  #
  # @see http://id.loc.gov/vocabulary/relators
  class MARCREL < ::RDF::Vocabulary("http://id.loc.gov/vocabulary/relators/")
    property :act
    property :adp
    property :anl
    property :anm
    property :ann
    property :app
    property :arc
    property :arr
    property :acp
    property :art
    property :ard
    property :asg
    property :asn
    property :att
    property :auc
    property :aut
    property :aqt
    property :aft
    property :aud
    property :aui
    property :aus
    property :ant
    property :bnd
    property :bdd
    property :blw
    property :bkd
    property :bkp
    property :bjd
    property :bpd
    property :bsl
    property :cll
    property :ctg
    property :cns
    property :chr
    property :cng
    property :cli
    property :clb
    property :col
    property :clt
    property :clr
    property :cmm
    property :cwt
    property :com
    property :cpl
    property :cpt
    property :cpe
    property :cmp
    property :cmt
    property :ccp
    property :cnd
    property :con
    property :csl
    property :csp
    property :cos
    property :cot
    property :coe
    property :cts
    property :ctt
    property :cte
    property :ctr
    property :ctb
    property :cpc
    property :cph
    property :crr
    property :crp
    property :cst
    property :cov
    property :cre
    property :cur
    property :dnc
    property :dtc
    property :dtm
    property :dte
    property :dto
    property :dfd
    property :dft
    property :dfe
    property :dgg
    property :dln
    property :dpc
    property :dpt
    property :dsr
    property :drt
    property :dis
    property :dbp
    property :dst
    property :dnr
    property :drm
    property :dub
    property :edt
    property :elg
    property :elt
    property :eng
    property :egr
    property :etr
    property :evp
    property :exp
    property :fac
    property :fld
    property :flm
    property :fpy
    property :frg
    property :fmo
    property :fnd
    property :gis
    property :hnr
    property :hst
    property :ilu
    property :ill
    property :ins
    property :itr
    property :ive
    property :ivr
    property :inv
    property :lbr
    property :ldr
    property :led
    property :lsa
    property :len
    property :lil
    property :lit
    property :lie
    property :lel
    property :let
    property :lee
    property :lbt
    property :lse
    property :lso
    property :lgd
    property :ltg
    property :lyr
    property :mfr
    property :mrb
    property :mrk
    property :mdc
    property :mte
    property :mod
    property :mon
    property :mcp
    property :msd
    property :mus
    property :nrt
    property :opn
    property :orm
    property :org
    property :oth
    property :own
    property :ppm
    property :pta
    property :pth
    property :pat
    property :prf
    property :pma
    property :pht
    property :ptf
    property :ptt
    property :pte
    property :plt
    property :prt
    property :pop
    property :prm
    property :prc
    property :pro
    property :pmm
    property :prd
    property :prg
    property :pdr
    property :pfr
    property :pup
    property :pbl
    property :pbd
    property :ppt
    property :rcp
    property :rce
    property :red
    property :ren
    property :rpt
    property :rps
    property :rth
    property :rtm
    property :res
    property :rsp
    property :rst
    property :rse
    property :rpy
    property :rsg
    property :rev
    property :rbr
    property :sce
    property :sad
    property :scr
    property :scl
    property :spy
    property :sec
    property :std
    property :sgn
    property :sng
    property :sds
    property :spk
    property :spn
    property :stm
    property :stn
    property :str
    property :stl
    property :sht
    property :srv
    property :tch
    property :tcd
    property :ths
    property :trc
    property :trl
    property :tyd
    property :tyg
    property :uvp
    property :vdg
    property :voc
    property :wit
    property :wde
    property :wdc
    property :wam
  end
end
